### ISSUE TITLE
[feature request] copy image

### ISSUE THREAD

**Issue by judgeou** [asadahimeka/yandere-masonry#10]
add button for copy image

**Comment by asadahimeka** [comment]
Temporarily you can use the browser context menu to copy image when you are in large image view mode.

![2022-11-23 21-6-10](https://user-images.githubusercontent.com/31837214/203555558-f10739d5-c321-4e9c-8fcf-b9f6bc4fbfcb.png)

![2022-11-23 210740](https://user-images.githubusercontent.com/31837214/203555578-0b923325-f05b-4aff-b75a-6c5ee1e96fae.png)

**Comment by asadahimeka** [comment]
v0.27.1 Modified.
