### ISSUE TITLE
非瀑布流模式下能否显示查看NSFW里的隐藏图片

### ISSUE THREAD

**Issue by asadahimeka** [asadahimeka/yandere-masonry#12]
非瀑布流模式下能否显示查看NSFW里的隐藏图片

_Originally posted by @ziya186

**Comment by asadahimeka** [comment]
@ziya186 , 是 yandere 站吗，可以登录后去设置 (https://yande.re/user/edit) 里改

**Comment by ziya186** [comment]
edit的tag很久以前久清空了，但是发现用瀑布流查看时会有些隐藏图片
