### ISSUE TITLE
Gelbooru图片下载无法识别下载是否完成

### ISSUE THREAD

**Issue by TIANzhefei** [asadahimeka/yandere-masonry#14]
![image](https://user-images.githubusercontent.com/61894565/212226012-953f5f50-12d9-4b0a-ae2b-959b1152f029.png)
点击下载键后，即使浏览器已经完成了下载，插件仍然会认为下载没有完成，无法继续下载其他图片。使用批量下载功能时则只能下载第一张图片。在yande.re和danbooru测试了一下，可以正常下载。

**Comment by asadahimeka** [comment]
好像是 Gelbooru 的运行环境有些问题导致 Tampermonkey 注入的函数回调不成功，目前去掉了 G 站下载时的加载状态判断，v0.28.0 已发布；另，网页下载限制比较多，还是建议使用输出下载地址功能，导出 txt 后使用迅雷、IDM 等下载工具批量下载
