### ISSUE TITLE
Sidebar tags translation broken in yande.re

### ISSUE THREAD

**Issue by keeptpa** [asadahimeka/yandere-masonry#15]
- Bugs appearence: It's not adding translation before the oringinal tags in the sidebar as it should in yande.re, but function  running well in other sites.

I think the [seletcor](https://github.com/asadahimeka/yandere-masonry/blob/17f37a07c5a20c299d0042e83b0dcf0d50d98c7d/dist/yandere-masonry.user.js#L224) that pushed into **setTagText** returns a empty set. But I am not major in js so not very sure about it. But, remove the "?tags=" in the selector nailed it.

CHS:

- BUG: yandere的左侧列表没有翻译成功，在其他站没问题。

捣鼓了一会儿后感觉[选择器](https://github.com/asadahimeka/yandere-masonry/blob/17f37a07c5a20c299d0042e83b0dcf0d50d98c7d/dist/yandere-masonry.user.js#L224)可能有问题？返回的似乎是空集。我没有用过js所以不太确定，但去掉 ?tags= 后倒是正常了

**Comment by asadahimeka** [comment]
我这边没问题欸，可能是翻译文件没有加载成功

<img width=700 src=https://user-images.githubusercontent.com/31837214/214212137-0c752848-8e76-40dc-959d-403116db35db.png >

**Comment by keeptpa** [comment]
嗯....这就很奇怪了，不过可以很明确的说，用于翻译的json是加载成功了的，我打印过
我还是认为是选择器存在问题，返回了一个空集，因此翻译tag的[遍历这部分](https://github.com/asadahimeka/yandere-masonry/blob/17f37a07c5a20c299d0042e83b0dcf0d50d98c7d/dist/yandere-masonry.user.js#L204)压根儿是没进去的。
但是既然问题不能复现，所以改起来应该挺麻烦的……
我先修改一个本地版本用吧，如果后面还有人出现同样问题可以试试看上面提到的方法。
谢谢作者了

**Comment by asadahimeka** [comment]
新年快乐
可能标签元素链接里没有 `?tags=` 就没取到集合
首页 (yande.re/post) 就翻译不成功吗，还是什么特定页面
或者可能是与其他什么脚本扩展之类的冲突了
先本地改着用吧 <img width=32 src=https://user-images.githubusercontent.com/31837214/214237746-f3a5420f-9f2e-4eff-b5a4-ce2cb483a6c2.png>

**Comment by keeptpa** [comment]
啊啊，我的错，是我没说清楚

是这样的，首页是能翻译的，不过首页的tag只有三个类别，【画师】【版权】【角色】
所以首页应该是不用 https://raw.githubusercontent.com/asadahimeka/yandere-masonry/main/src/data/tags_cn.json 的，对吧

_https://yande.re/post?tags=_    
进行tag搜索时这样的，就不能翻译了，浏览这里时，汉化tag的选择器获取的集合就是空集
然后脚本的话，我新做的系统，chrome油猴只有这一个脚本，没有安装任何其他脚本。
其他的插件也没有运行

**Comment by keeptpa** [comment]
更新：发现是登录后就不能正常汉化了
<img width="419" alt="image" src="https://user-images.githubusercontent.com/31382232/214241308-7125fa8a-4816-4511-a2b2-fd7f0f3aadef.png">
可以看到我这里登陆后，标签前的 + 和 - 号全部带有 no-browser-link 进而被过滤掉了

**Comment by asadahimeka** [comment]
我猜是因为你在 Y 站 [设置](https://yande.re/user/edit) 里打开了这个开关，然后和登录之前的查看模式不一样了，这个 browse 模式我并没有适配 <img width="32" src="https://user-images.githubusercontent.com/31837214/214237746-f3a5420f-9f2e-4eff-b5a4-ce2cb483a6c2.png" style="max-width: 100%;">

<img width=600 src=https://user-images.githubusercontent.com/31837214/214251191-80134777-6e1c-4116-97ac-07f6d3a7a8af.png >

**Comment by keeptpa** [comment]
我想可能确实是因为这个了，但是我并没有手动调整他的印象
总之……问题清晰解决了，谢谢作者了
