### ISSUE TITLE
建议增加 打开文件源头 选项

### ISSUE THREAD

**Issue by ZYV5ge** [asadahimeka/yandere-masonry#17]
建议增加 打开文件源头 选项，方便跟踪原作者！

谢谢

**Comment by asadahimeka** [comment]
目前是有来源按钮的，如果没有那就是发布者没有填写来源

![image](https://user-images.githubusercontent.com/31837214/221394224-7c9df1a7-4120-4cea-a82e-8bd48e1cee29.png)

**Comment by asadahimeka** [comment]
由于长时间未得到回复，本 issue 将被关闭，若还有问题的话请重新打开本 issue
