### ISSUE TITLE
rule34.xxx is not working

### ISSUE THREAD

**Issue by Mokkita** [asadahimeka/yandere-masonry#22]
rule34.xxx is not working but Paheal is working good

**Comment by asadahimeka** [comment]
It works on my side, if yours doesn't, you may have to visit the source site first and use this script after passing the captcha.

<img width=600 src="https://github.com/asadahimeka/yandere-masonry/assets/31837214/4cb47ac8-406c-4a7e-b3b4-2c4d98690804" alt >
