### ISSUE TITLE
可不可以在瀑布流模式下 直接显示加载原图并在瀑布流模式下直接显示?

### ISSUE THREAD

**Issue by XiaoYingYo** [asadahimeka/yandere-masonry#23]

**Comment by asadahimeka** [comment]
当图片列表布局设置为「Masonry」且瀑布流列数设置为小于6时，列表图片会以大图加载；其他布局的列表图片暂时只能以缩略图加载；由于原图体积比较大，为避免给服务器造成压力，列表图片不会用原图。
