### ISSUE TITLE
默认瀑布流模式

### ISSUE THREAD

**Issue by xushet** [asadahimeka/yandere-masonry#24]
怎么设置浏览yande.re时自动启用瀑布流模式？
![image](https://github.com/asadahimeka/yandere-masonry/assets/34502902/506c8318-fb39-4c91-bc31-14e493dc01ed)
每次都要点一下

**Comment by asadahimeka** [comment]
直接访问此链接： https://yande.re/post?_wf=1

**Comment by asadahimeka** [comment]
@xushet ，v0.32.0 添加自动进入瀑布流模式的开关
