### ISSUE TITLE
下载列表选择大图和原图选择失效

### ISSUE THREAD

**Issue by skshuail** [asadahimeka/yandere-masonry#26]
前几天还能正常使用 自由切换大图和原图输出地址下载 现在只能下载原图了 （点了大图选项输出地址还是原图的）
Chrome 版本 121.0.6167.185（正式版本） （64 位）  篡改猴 v5.0.1

有变动的操作： 修改了yandere的host (之前都用的魔法 
浏览器新增了IDM 

不知道是不是和gelbooru冲突然后bug了 发现g站的瀑布贴下载列表是没有大图原图选择的 y站才有

不太会发lssue 大佬见谅 请求回复 谢谢！！

**Comment by skshuail** [comment]
又试了试...好像其实是正常的？ 切换的时候看见有一些后缀变成jpg了 有些还是png格式 是和图片上传者有关吗
顺便再问问批量下图的时候大佬自带的下载经常假死是什么原因（丢着下载看别的网页它下载就停了，一直挂着界面就正常 ）然后用链接批量IDM和迅雷很多都会超时      还有yande下载特别特别慢 gel就特别快 想请问是正常的吗 有解决方法吗   谢谢！！

**Comment by asadahimeka** [comment]
@skshuail 
> 发现g站的瀑布贴下载列表是没有大图原图选择的 y站才有

目前只有 moebooru 系的站点(Y 站、K 站)才有大图(JPG)地址，其他 danbooru/gelbooru 系的站点只有样品图(品质较差)和原图地址

> 点了大图选项输出地址还是原图的
> 切换的时候看见有一些后缀变成jpg了 有些还是png格式 是和图片上传者有关吗

moebooru 系站点有些图片也是没有大图(JPG)地址的，原因未知，这种情况下大图地址会被设置为原图地址

> 顺便再问问批量下图的时候大佬自带的下载经常假死是什么原因（丢着下载看别的网页它下载就停了，一直挂着界面就正常 

假死可能是因为标签页被浏览器休眠了，所以下载就停了

> 然后用链接批量IDM和迅雷很多都会超时 还有yande下载特别特别慢 gel就特别快 想请问是正常的吗 有解决方法吗

可能是 G 站的服务器比 Y 站好些吧（

使用 IDM 等下载器时建议检查下代理是否生效，如果直连的话速度可能会很慢，鉴于目前的网络环境，能使用魔法还是用吧。如果用了还是慢，那就换个快点的魔法（ 

P.S. 自带的下载实现得很简陋，图片太多的场景下体验很差，建议使用专用的下载工具，这里有我之前看到过的两个工具，你可以试试

[MoeLoaderP 二次元图片下载器](https://github.com/xplusky/MoeLoaderP)

[gallery-dl](https://github.com/mikf/gallery-dl)

**Comment by skshuail** [comment]
@asadahimeka 感谢大佬耐心回复 谢谢！！

关于站点的大图 原图问题那看来和插件运行无关了 （本来是个原图爱好者 后来不知道在哪看的说法一般存图存jpg足矣png都是修图用的 就能选大图选大图了 毕竟网络情况下起来还快不少）

至于下载的问题目前换成IDM后基本上可以挂着干别的事了 大佬贴的两个git还是略微专业（感谢指路） IDM对我这种小白来说够用了  不过不清楚为什么g站导出的下载列表IDM是下载不了的  这个倒是不影响 我的网络配合大佬插件自带的下载下的很快 可能真的就是g站比y站服务器好吧233

题外话 感觉这些图站各有长处 G站感觉乱七八糟比较多 Y站感觉瑟瑟多  danbooru有会员制  想问问这么多图站哪些比较推荐好用

**Comment by asadahimeka** [comment]
@skshuail，平时主要看的还是 pixiv，Y 站是看一下 p 站没有的图，然后除了 Y 站，其他的站点我都不怎么用😂

以下是个人对这些图站的刻板印象（
- yande.re 个人常用，图片质量较高，但相对数量和更新速度不如 D 站，有 pools(图集) ；然后找 p 站没有的差分
- konachan.com 找 PC 壁纸多用，一般是横向图，纵向的图会被旋转为横向的；数量与更新速度跟 Y 站差不多
- konachan.net K 站表站，只显示安全的图
- danbooru.donmai.us 量大、更新快，但有很多图质量一般；好像最开始的 AI 绘图就是喂的 D 站的数据 ；有动图
- gelbooru.com 个人感觉跟 D 站差不多，好图需要自己发掘 ；有动图
- rule34.xxx If it exists, there is porn of it.  怪怪的站，总感觉全是 furry 图，但是量大、更新速度快；有动图
- lolibooru.moe 看域名就知道🤣
- sakugabooru.com 全是动画切片，作画厨应该挺喜欢
- safebooru.org 像是 D 站表站一样，不太清楚；都是安全图
- aibooru.online 全是 AI 生成的图片，更新速度也还蛮快的
- behoimi.org 也即 3dbooru，cos 图站，更新速度很慢
- realbooru.com 全是真人图片，还有很多辣眼图
- tbib.org 没怎么用
- xbooru.com 没怎么用
- booru.allthefallen.moe 也即 atfbooru，没怎么用

**Comment by skshuail** [comment]
@asadahimeka  大佬nb ！！ 问了一堆不相干的个人问题 十分感谢解答！！

其实一切使然都是群友发瑟图...然后顺着当中国式英雄 然后发现y站居然能看到fanbox之类的图  加上本身就有收藏的爱好  就....
 
moebooru 系的站点(Y 站、K 站)是不收录AI制作的图片的吗 貌似都没看见 (主要蓝P的作者ID换到Y站我还是通过识图网站跳转的，但是识图网站对AI比较笨，只能靠SauceNAO 侧边有G站 Y站 的跳转链接 
  上面看大佬说也在Y看P没有的差分 有什么方便快捷的办法查到作者在Y站的Tag吗 

话说AI炼的基本上都找不到 如 SauceNAO，最多Google/Yande能追溯到NGA，贴吧之类的求图贴  请问AI的是有专门识图网站吗

再次感谢大佬！提前祝元宵节快乐！~

**Comment by skshuail** [comment]
站点+google确实可以（甚至中文ID都行） 感谢 ！ 额外发现Danbooru的 [Artists] 选项可以输入P的作者URL就有对应tag ，G站 Y站没发现相同功能。不过 AI的画师不行 AI专门的图站也没有
