### ISSUE TITLE
本地标签黑名单能导出和导入吗 

### ISSUE THREAD

**Issue by pansuto** [asadahimeka/yandere-masonry#27]
换浏览器或者电脑的时候要一个一个打出来按一次回车，或者支持逗号间隔标签也行能直接复制一串标签不用打一个回车一下

**Comment by asadahimeka** [comment]
@pansuto ，v0.32.0 已发布，添加了剪贴板导入导出标签黑名单功能

![2024-2-24 20-37-30](https://github.com/asadahimeka/yandere-masonry/assets/31837214/e73ba598-fc8a-4b04-8340-f2b58bcc234b)
![2024-2-24 20-37-39](https://github.com/asadahimeka/yandere-masonry/assets/31837214/6f3a8cfe-35b9-4105-a7ab-762292d9b1d2)
