### ISSUE TITLE
Column Count Not Validating in Justified Layout

### ISSUE THREAD

**Issue by TragicNet** [asadahimeka/yandere-masonry#30]
Cannot change column count in Justified Layout, results in having to change change to masonry layout, changing columns, switching back to justified layout

**Comment by asadahimeka** [comment]
In view of the image loading speed and to avoid putting pressure on the origin site's server, the images list should use lower-definition thumbnails as much as possible.

You can choose the number of columns to display. When the number of columns is not selected `Auto` and the number of columns is <= 6, the image will be displayed with `sample_url` (that is, the size in the details popup).

The filesize of the original image is too large. Some images are often over 10MiB in size. 
IMO, If it's just for display, there's no need to use the original file.

![image](https://github.com/asadahimeka/yandere-masonry/assets/31837214/98b8dc87-7813-4cbb-9b6b-680af7f9fbf5)

**Comment by asadahimeka** [comment]
* { font-size: 13px; font-family: 'MS Pゴシック', sans-serif;}p, ul, ol, blockquote { margin: 0;}a { color: #0064c8; text-decoration: none;}a:hover { color: #0057af; text-decoration: underline;}a:active { color: #004c98;}



As a temporary solution, you may switch the layout to `Masonry` first, select the number of columns, and then switch back to `Justified`.




----- Original Message -----




From: "TragicNet" ***@***.***>

To: "asadahimeka/yandere-masonry" ***@***.***>

Cc: "Comment" ***@***.***>

Date: 2024/03/26 火 20:53

Subject: Re: [asadahimeka/yandere-masonry] Bad Thumbnail Quality (Issue #30)







In view of the image loading speed and to avoid putting pressure on the origin site's server, the images list should use lower-definition thumbnails as much as possible.

You can choose the number of columns to display. When the number of columns is not selected Auto and the number of columns is <= 6, the image will be displayed with sample_url (that is, the size in the details popup).

The filesize of the original image is too large. Some images are often over 10MiB in size.

 IMO, If it's just for display, there's no need to use the original file.

image.png (view on web)

I am using, the justified view, and there is no column selection there, so losing image quality there defeats the purpose of that layout making it pointless.

**Comment by TragicNet** [comment]
> As a temporary solution, you may switch the layout to `Masonry` first, select the number of columns, and then switch back to `Justified`.
> […](#)
> ----- Original Message ----- From: "TragicNet" ***@***.***> To: "asadahimeka/yandere-masonry" ***@***.***> Cc: "Comment" ***@***.***> Date: 2024/03/26 火 20:53 Subject: Re: [asadahimeka/yandere-masonry] Bad Thumbnail Quality (Issue #30) In view of the image loading speed and to avoid putting pressure on the origin site's server, the images list should use lower-definition thumbnails as much as possible. You can choose the number of columns to display. When the number of columns is not selected Auto and the number of columns is <= 6, the image will be displayed with sample_url (that is, the size in the details popup). The filesize of the original image is too large. Some images are often over 10MiB in size. IMO, If it's just for display, there's no need to use the original file. image.png (view on web) I am using, the justified view, and there is no column selection there, so losing image quality there defeats the purpose of that layout making it pointless. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Ok this worked, I am changing the issue title and description accordingly.

**Comment by asadahimeka** [comment]
Added a switch in v0.32.2.

![image](https://github.com/asadahimeka/yandere-masonry/assets/31837214/359a3c61-5069-4b5f-86ab-d3e2c46c4d24)

**Comment by TragicNet** [comment]
Although this is 1 extra step for the user, it does the job, marking this closed.
Also the switch text can be improved, normal users won't understand this easily.
