### ISSUE TITLE
Feature Request: “Save to Favorites” Button for Gelbooru

### ISSUE THREAD

**Issue by sharpsalat** [asadahimeka/yandere-masonry#33]
Dear Yandere-Masonry Developer,
I propose adding a “Save to Favorites” button for the Gelbooru website within the Yandere-Masonry Chrome extension. Currently, users need to open each image link individually to save it. Additionally, consider adding a keyboard shortcut (e.g., “F”) alongside the UI button for even quicker access.
There is an extension for example of implementing  'Press F to Save':
[Press F to favorite - Gelbooru](https://sleazyfork.org/en/scripts/450947-press-f-to-favorite-gelbooru)
Thank you for considering this enhancement!

Many thanks for considering my request.

**Comment by asadahimeka** [comment]
@sharpsalat, sorry for the late reply.
Favorite button for danbooru/gelbooru/rule34 has been added in v0.32.3.
And for some reasons, the "F" key shortcut only works in the detail popup.

**Comment by sharpsalat** [comment]
@asadahimeka Awesome :D Thanks
