### ISSUE TITLE
[Feature Request]: option to turn on checkboxes at the corners of images

### ISSUE THREAD

**Issue by Aosneg** [asadahimeka/yandere-masonry#34]
Hello! 

I would like to request a feature that allows users to turn on checkboxes at the corner of each image as an alternative to the "add to download list" button, which currently appears when we hover over an image. I believe this would be more convenient than the existing "add to download list" option because it provides a visual indication for images that have already been checked or not been checked yet, and it is easier to click on the corner than on a button in the bottom middle. Here is an example:
![Untitled-3](https://github.com/asadahimeka/yandere-masonry/assets/138026259/56a7d6ac-9dc5-40dc-92af-2fc54180386a)

Thank you!

**Comment by asadahimeka** [comment]
@Aosneg, sorry for the late reply. This feature has been added in v0.32.3.

![image](https://github.com/asadahimeka/yandere-masonry/assets/31837214/89704243-6a99-4314-9477-fa59bd9c54f0)
![image](https://github.com/asadahimeka/yandere-masonry/assets/31837214/d7129bc9-1b14-4846-878e-ac344c286da2)

**Comment by Aosneg** [comment]
Oh, cool! Thank you!
