### ISSUE TITLE
[建议]增加后台新标签页打开

### ISSUE THREAD

**Issue by rcyggdra** [asadahimeka/yandere-masonry#36]
设置里添加开关，控制<新标签页打开>打开按钮是否后台打开。

**Comment by asadahimeka** [comment]
目前来看好像没有办法使用 js 在后台打开新标签页，等我看看把按钮改成 `<a>` 标签，到时候可以用 <kbd>Ctrl</kbd> + 鼠标左键点击，或者鼠标中键点击在后台打开

**Comment by asadahimeka** [comment]
@rcyggdra , v0.33.4 已将新标签按钮修改 `<a>` 标签

**Comment by rcyggdra** [comment]
> @rcyggdra , v0.33.4 已将新标签按钮修改 `<a>` 标签

感谢更新，可以使用鼠标中键后台打开了。
