### ISSUE TITLE
yande建议允许可选使用网站默认排序，而不是使用order:id_desc+holds:true

### ISSUE THREAD

**Issue by Coarisu** [asadahimeka/yandere-masonry#38]
最近发现打开瀑布流之后与默认首页的图片不一致，研究发现yande默认应该是按照解除hold的时间排序，插件的瀑布流模式则是和使用站内搜索功能“搜索”holds:true order:id_desc 后一致的顺序。
希望能允许可选、可自定义排序。现在瀑布流开启前后不一致，会造成一些困惑；hold挂起的图片可能还未完成标签、来源编辑等操作，早早展示不一定更好。

**Comment by asadahimeka** [comment]
那如果使用 `holds:false` 搜索的话是不是就跟首页的图片顺序一致了？

**Comment by Coarisu** [comment]
> 那如果使用 `holds:false` 搜索的话是不是就跟首页的图片顺序一致了？如果是这样的话我有空加上个开关

并不是，如果yande主页同时搜索 `order:id_desc` 则一致。
![Snipaste_2024-06-19_22-14-21](https://github.com/asadahimeka/yandere-masonry/assets/45917249/273f4a85-c4b5-4d9f-ae71-a82bca0f7d97)
上图左侧使用瀑布流，搜索 `holds:false` ，右侧搜索保持空白默认，可以看到图片顺序并不一致。
![Snipaste_2024-06-19_22-15-25](https://github.com/asadahimeka/yandere-masonry/assets/45917249/52c0a425-172a-4278-acff-b05136219343)
如果左侧使用 `holds:false` 右侧使用 `order:id_desc` 则一致。

实现起来或许会有些困难？看起来现在是直接使用图片id顺序拉取的，而booru图站的顺序并不完全遵循id顺序。

**Comment by asadahimeka** [comment]
看了下 [moebooru](https://github.com/moebooru/moebooru) 的源码，好像主页图片列表的默认顺序是按 `index_timestamp` 降序排的，猜着可能是图片的更新时间，比如编辑过了标签等元信息后会更新到列表前面。而调用 API 的话是默认按照 ID 降序排的。

非 API 调用的情况下也即主页列表查询会自动过滤 _挂起(is_held)_ 的图片，当 API 调用传入 `holds:false` 时，两者之间的差别应该就在这个 `index_timestamp` 的排序上了。

但目前没有找到可以按 `index_timestamp` 排序的标签语法，在我个人看来按 ID 降序就可以了，如果按照这个 `index_timestamp` 排的话可能就给我一种「这张图不是看过了吗，怎么又出来了」的感觉。

改进的话我觉得就加上一个开关，打开后调用 API 时会自动追加 `holds:false` 就可以了，主要需求应该还是隐藏挂起的图片。
或者可以加一个 _默认标签_ 的设置，可以自己定义默认传入的 tags。

最后的办法可能就是我不调用 API 了，直接请求 HTML 页面后解析，这样子顺序肯定是一致的，但是有些信息可能会缺失。

<img width=500 src=https://github.com/asadahimeka/yandere-masonry/assets/31837214/a2348419-49e1-43f8-b194-90d5cca0cc0d>

<img width=500 src=https://github.com/asadahimeka/yandere-masonry/assets/31837214/c872dd7c-188f-43ec-a9d2-afdb8ff2e6be>

<img width=500 src=https://github.com/asadahimeka/yandere-masonry/assets/31837214/befcf57b-9668-4968-99a0-693d40292363>

---

> 我发现如果设置了api的话，顺序就是正确的

至于这个倒是不太清楚了，设置了 api 是指填入了 api_key 吗？我觉得这个应该不会影响排序

**Comment by Coarisu** [comment]
从个人的使用经验来说，yande默认的排序不太会出现重复看到同一张图的情况，或许如果图片拥有者能够重复hold的话能重新刷新排序到前列？然而这可能没啥意义。
我有个习惯是每天都会去yande浏览更新的图片，将喜欢的图片另存到电脑上，所以我几乎可以确定并不是任意操作都会导致排到前面，因为如果是这样，不可能几年了没有察觉……好像也不是完全不可能？

是的，我在设置了api_key之后，顺序就一致了，但是只有第一页是一致的，向下滑动又会回到以ID排序的状态。

其实按ID排也没啥问题就是了，就是进入瀑布流的时候与进入之前的图片不一致，很奇怪。



来自 MEIZU 20 Pro



-------- 原始邮件 --------
发件人：Sakura Yumine ***@***.***>
时间：2024年6月20日 14:22
收件人：asadahimeka/yandere-masonry ***@***.***>
抄送：Coarisu ***@***.***>,Author ***@***.***>
主题：Re: [asadahimeka/yandere-masonry] yande建议允许可选使用网站默认排序，而不是使用order:id_desc+holds:true (Issue #38)


看了下 moebooru<https://github.com/moebooru/moebooru> 的源码，好像主页图片列表的默认顺序是按 index_timestamp 降序排的，猜着可能是图片的更新时间，比如编辑过了标签等元信息后会更新到列表前面。而调用 API 的话是默认按照 ID 降序排的。

非 API 调用的情况下也即主页列表查询会自动过滤 挂起(is_held) 的图片，当 API 调用传入 holds:false 时，两者之间的差别应该就在这个 index_timestamp 的排序上了。

但目前没有找到可以按 index_timestamp 排序的标签语法，在我个人看来按 ID 降序就可以了，如果按照这个 index_timestamp 排的话可能就给我一种「这张图不是看过了吗，怎么又出来了」的感觉。

改进的话我觉得就加上一个开关，打开后调用 API 时会自动追加 holds:false 就可以了，主要需求应该还是隐藏挂起的图片。
或者可以加一个 默认标签 的设置，可以自己定义默认传入的 tags。

最后的办法可能就是我不调用 API 了，直接请求 HTML 页面后解析，这样子顺序肯定是一致的，但是有些信息可能会缺失。

image.png (view on web)<https://github.com/asadahimeka/yandere-masonry/assets/31837214/a2348419-49e1-43f8-b194-90d5cca0cc0d> image.png (view on web)<https://github.com/asadahimeka/yandere-masonry/assets/31837214/c872dd7c-188f-43ec-a9d2-afdb8ff2e6be> image.png (view on web)<https://github.com/asadahimeka/yandere-masonry/assets/31837214/befcf57b-9668-4968-99a0-693d40292363>
________________________________

我发现如果设置了api的话，顺序就是正确的

至于这个倒是不太清楚了，设置了 api 是指填入了 api_key 吗？我觉得这个应该不会影响排序

**Comment by asadahimeka** [comment]
这个问题从脚本刚开始开发时就有了：https://github.com/asadahimeka/yandere-masonry/issues/2#issue-1309697242，目前来看也没什么好办法，我只能说加一个默认 holds:false 了

**Comment by Coarisu** [comment]
> 这个问题从脚本刚开始开发时就有了：[#2 (comment)](https://github.com/asadahimeka/yandere-masonry/issues/2#issue-1309697242)
> 
> 目前来看也没什么好办法，我只能说加一个默认 holds:false 了

我是看到您博客文章才发现这是一个已知情况。
那么看起来这是moebooru的API输出内容与首页内容不一致，并且没有提供相同排序的接口？
若是这样可能确实没什么好办法，至于holds:false提供一个默认关闭的开关应该不错，但是默认false可能并不可取。
毕竟按照ID排序的情况下，新解除hold的图片并不会出现在开头，而是会被ID序列更新的图片推到后面。
考虑到holds:false并不是完全没有意义（比如可以保证下载到的图片拥有比较完整标签信息），提供一个开关应该不错。

**Comment by asadahimeka** [comment]
新加了两个设置，可以更新到 v0.33.4 测试一下

![image](https://github.com/asadahimeka/yandere-masonry/assets/31837214/109c9ce2-1d20-48cc-85f4-8bea6815a3ef)

**Comment by Coarisu** [comment]
> 新加了两个设置，可以更新到 v0.33.4 测试一下
> 
> 解析 HTML 获取数据的话，顺序是肯定一样的
> 
> ![image](https://private-user-images.githubusercontent.com/31837214/341500321-109c9ce2-1d20-48cc-85f4-8bea6815a3ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MDM4NDIsIm5iZiI6MTcxODkwMzU0MiwicGF0aCI6Ii8zMTgzNzIxNC8zNDE1MDAzMjEtMTA5YzljZTItMWQyMC00OGNjLTg1ZjQtOGJlYTY4MTVhM2VmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDE3MTIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlYWE1M2ZkMGUzZmQ4ZjcxYTEzODZjMThjODI1YzZmMTQ0YTViMDhhZmFiNDdkMGVlZjRjNTlhMmFlMjFlM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.StN96V19MKCgSQvTtpAIpGTlr-3qaNl4zQ4mTyNKwNc)

使用了第二个选项，效果确实符合预期了，也没有发现什么常用功能缺失。
我不是很懂代码，这应该是个不小的工程吧……速度是真的快……

其实其他图站也有相同的情况，或许应该考虑给konachan等站点也增加类似功能？

最后感谢功能实现，瀑布流模式浏览起来真的方便和直观很多。

**Comment by asadahimeka** [comment]
之前就有解析 HTML 的想法了😂，做了一些前期准备，主要是怕后期 HTML 结构变动会导致获取不到数据，一直就没搞；
其他 moebooru 站点等我看看它们的页面结构是否一致后再考虑，我平常主要用的还是 Y 站😹
