### ISSUE TITLE
使用键盘按键切换图片

### ISSUE THREAD

**Issue by someshittyeletronicmusicband** [asadahimeka/yandere-masonry#6]
首先，对不起，我不会说中文，我正在使用翻译设备。

你能实现一种用 A/D 或键盘箭头等键切换图片的方法吗？ 有时您可能只想使用键盘进行导航。

感谢这个惊人的脚本！

**Comment by asadahimeka** [comment]
@someshittyeletronicmusicband , v0.25.2 has been released. Now you can use `A/D/←/→` key to load prev or next post in the detail popup. Btw, i18n support is working in progress.
