### ISSUE TITLE
Option to select locale

### ISSUE THREAD

**Issue by someshittyeletronicmusicband** [asadahimeka/yandere-masonry#7]
By default the script sets the locale to zh_CN (which makes every website chinese) and you have to modify the code every time it updates to set it to another locale like en_US. Can you an option somewhere on the interface? Maybe you can just detect the browser language instead.

**Comment by asadahimeka** [comment]
@someshittyeletronicmusicband 

v0.26.0 released, added moebooru locale select as below

and masonry mode i18n support is still WIP

![image](https://user-images.githubusercontent.com/31837214/201269438-0eb3337b-a1d1-485f-a040-748d589002db.png)

**Comment by ziya186** [comment]
非瀑布流模式下能否显示查看NSFW

**Comment by asadahimeka** [comment]
Masonry mode i18n supported in v.0.29.0
